
# docker run -p 80:80 \
#   -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf \
#   -v $(pwd)/public:/usr/share/nginx/html/public \
#   nginx:latest

user nginx;

error_log /var/log/nginx/error.log info;
pid /var/run/nginx.pid;

worker_processes 2;

events {
    worker_connections 64;
}

http {
    access_log /var/log/nginx/access.log;
    log_format simple '$remote_addr $request $status';
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html/;
            index index.html;
        }

        location /public/ {
            alias /usr/share/nginx/html/public/;
            autoindex on; #Каталог файлов для удобства
        }

        location /partner/ {
            proxy_pass https://mai.ru;
        }
    }
}
