# Generated by Django 5.0 on 2026-05-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
