# Generated by Django 5.0 on 2026-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_alter_course_description_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio2',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='some_test_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
