# Generated by Django 5.0 on 2026-05-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_remove_userprofile_bio2_userprofile_some_test_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='some_test_text',
        ),
    ]
